// Generated by https://quicktype.io

export interface Racer {
  id: number;
  type: string;
  belongsTo: number;
  plateNum: number;
  firstName: string;
  lastName: string;
  sex: string;
  category: string;
  address: string;
  city: string;
  postalCode: string;
  phoneNum: string;
  attendedCount: number;
  attended: string;
  totalPoints: number;
  paid: string;
}
